#!/bin/bash



#==============================================================================
#
#       FILE:           virtual_backup
#
#       DESCRIPTION:    Creates monthly tarball of virtual machine
#
#
#       DEPENDENCIES:   rsync
#       
#       AUTHOR:         Charl Potgieter
#
#==============================================================================


#==============================================================================
#                       Configuration Options
#==============================================================================

# For both standard and error logs
LogPath=/srv/samba/Documents_Charl/Computer_Technical/Logs

#Path details for mirror backup of system itself excluding data
# ***** THIS IS A MIRROR FILES IN DESTINATION NOT IN SOURCE WILL BE ***********
# ***** DELETED IN THE DESTINATION PATH ***************************************
OS_SourcePath=/
OS_TarDestinationPath="/srv/samba/Documents_Charl/010_EncryptForCloudBackup\
/ArchSystemBackups/ArchServerTarballs"



# SPACE sperated list of locations to be excluded from systems backup
# list Exclusions below are modified from Arch Wiki
# https://wiki.archlinux.org/index.php/Full_system_backup_with_rsync
OS_Exclusions="/dev /proc /sys /tmp /run /mnt /media /srv/samba /lost+found"


#====FUNCTION==================================================================
#       Name:           system_mirror_tarball
#       Description:    Mirror system as a tarball (excluding data)
#       Paramaters:     None
#       Returns:        None
#==============================================================================

system_mirror_tarball() {

        # Tarball is created in addition to standard backup due to possible
        #  difficulty with longer pathnames in some environments e.g. windows
        # and cloud backups.
        # refer here for exclusions (arch wiki rsync backups)
        # https://wiki.archlinux.org/index.php/Full_system_backup_with_rsync
        # /srv is also excluded as it contains the mounted files used for
        # samba share

        Log="$LogPath/$date.ArchServerTarBackupLog.txt"
        ErrorLog="$LogPath/$date.ArchServerTarBackupErrorLog.txt"
        OS_TarDestinationFile=$OS_TarDestinationPath/$date.ArchServerBackup.tar.gz

        # Create an exclusion array.  Variable expanstion takes place after
        # brace expanion so can't use a brace expansion solution
        excl_array=()
        for  i in $OS_Exclusions; do
                excl_array+=(--exclude="$i")
        done

        if [ $DayOfMonth -eq 1 ]
        then
               tar "${excl_array[@]}"  -czpvf $OS_TarDestinationFile \
                       $OS_SourcePath >$Log 2>$ErrorLog
        fi

}






#==============================================================================
#                               MAIN PROGRAM
#==============================================================================


date=$(date "+%m%d")
DayOfMonth=$(date +%d)

system_mirror_tarball
