#!/bin/bash



#==============================================================================
#
#       FILE:           virtual_backup
#
#       DESCRIPTION:    Creates monthly tarball of virtual machine
#
#
#       DEPENDENCIES:   rsync
#       
#       AUTHOR:         Charl Potgieter
#
#==============================================================================


#==============================================================================
#                       Configuration Options
#==============================================================================

# For both standard and error logs
LogPath=/media/sf_Documents_Charl/Computer_Technical/Logs

#Path details for mirror backup of system itself excluding data
OS_SourcePath=/
OS_TarDestinationPath="/media/sf_Documents_Charl/010_EncryptForCloudBackup\
/ArchSystemBackups/ArchVirtTarballs"


# SPACE sperated list of locations to be excluded from systems backup
# list Exclusions below are modified from Arch Wiki
# https://wiki.archlinux.org/index.php/Full_system_backup_with_rsync
OS_Exclusions="/dev /proc /sys /tmp /run /mnt /media /srv/samba /lost+found /media"


#====FUNCTION==================================================================
#       Name:           system_mirror_tarball
#       Description:    Mirror system as a tarball (excluding data)
#       Paramaters:     None
#       Returns:        None
#==============================================================================

system_mirror_tarball() {

        # Tarball is created due difficulty with longer pathnames
        # in some environments e.g. windows
        # and cloud backups.
        # refer here for exclusions (arch wiki rsync backups)
        # https://wiki.archlinux.org/index.php/Full_system_backup_with_rsync
        # /srv and /media are also excluded as it contains the mounted files used for
	# samba share (not currently used) and virtualbox shared folders

        Log="$LogPath/$date.ArchVirtTarBackupLog.txt"
        ErrorLog="$LogPath/$date.ArchVirtTarBackupErrorLog.txt"
        OS_TarDestinationFile=$OS_TarDestinationPath/$date.ArchVirtBackup.tar.gz

        # Create an exclusion array.  Variable expanstion takes place after
        # brace expanion so can't use a brace expansion solution
        excl_array=()
        for  i in $OS_Exclusions; do
                excl_array+=(--exclude="$i")
        done

        if [ $DayOfMonth -eq 14 ]
        then
               tar "${excl_array[@]}"  -czpvf $OS_TarDestinationFile \
                       $OS_SourcePath >$Log 2>$ErrorLog
        fi

}






#==============================================================================
#                               MAIN PROGRAM
#==============================================================================


date=$(date "+%m%d")
DayOfMonth=$(date +%d)

system_mirror_tarball
